create table "public"."natures" (
    "id" bigint generated by default as identity not null,
    "createdAt" timestamp with time zone not null default now(),
    "title" text not null,
    "description" text not null,
    "natureImg" text not null,
    "user_id" uuid not null default gen_random_uuid(),
    "tag" text[]
);


alter table "public"."natures" enable row level security;

CREATE UNIQUE INDEX natures_pkey ON public.natures USING btree (id);

alter table "public"."natures" add constraint "natures_pkey" PRIMARY KEY using index "natures_pkey";

grant delete on table "public"."natures" to "anon";

grant insert on table "public"."natures" to "anon";

grant references on table "public"."natures" to "anon";

grant select on table "public"."natures" to "anon";

grant trigger on table "public"."natures" to "anon";

grant truncate on table "public"."natures" to "anon";

grant update on table "public"."natures" to "anon";

grant delete on table "public"."natures" to "authenticated";

grant insert on table "public"."natures" to "authenticated";

grant references on table "public"."natures" to "authenticated";

grant select on table "public"."natures" to "authenticated";

grant trigger on table "public"."natures" to "authenticated";

grant truncate on table "public"."natures" to "authenticated";

grant update on table "public"."natures" to "authenticated";

grant delete on table "public"."natures" to "service_role";

grant insert on table "public"."natures" to "service_role";

grant references on table "public"."natures" to "service_role";

grant select on table "public"."natures" to "service_role";

grant trigger on table "public"."natures" to "service_role";

grant truncate on table "public"."natures" to "service_role";

grant update on table "public"."natures" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."natures"
as permissive
for all
to public
using (true);




